"""sprint 2: inventory, forecasting, kitchen ops, system config

Revision ID: 7d60658b3d0f
Revises: af0fbfd50575
Create Date: 2026-09-11 16:51:24.473585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d60658b3d0f'
down_revision: Union[str, None] = 'af0fbfd50575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('ingredient_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('system_config',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('default_low_stock_threshold', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('leftover_rate_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('prep_deviation_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('portions_per_staff_ratio', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('monthly_budget_limit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('near_expiry_window_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('forecasts',
    sa.Column('forecast_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('meal_period', sa.String(length=20), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.menu_item_id'], ),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    op.create_table('leftover_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('service_period_date', sa.Date(), nullable=False),
    sa.Column('prepared_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('leftover_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('leftover_level', sa.String(length=20), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.menu_item_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('meal_period', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.menu_item_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('restocking_requests',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('urgency', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('stock_adjustments',
    sa.Column('adjustment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('adjusted_quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('reason_category', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('adjustment_id')
    )
    op.create_table('stock_batches',
    sa.Column('batch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('forecast_accuracies',
    sa.Column('accuracy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('accuracy_error', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.forecast_id'], ),
    sa.PrimaryKeyConstraint('accuracy_id'),
    sa.UniqueConstraint('forecast_id')
    )
    op.create_table('prep_recommendations',
    sa.Column('recommendation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('meal_period', sa.String(length=20), nullable=False),
    sa.Column('recommended_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.forecast_id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.menu_item_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_table('prep_confirmations',
    sa.Column('confirmation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deviation_reason', sa.Text(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['prep_recommendations.recommendation_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('confirmation_id'),
    sa.UniqueConstraint('recommendation_id')
    )
    op.create_foreign_key(None, 'recipe_ingredient_links', 'ingredients', ['ingredient_id'], ['ingredient_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_ingredient_links', type_='foreignkey')
    op.drop_table('prep_confirmations')
    op.drop_table('prep_recommendations')
    op.drop_table('forecast_accuracies')
    op.drop_table('stock_batches')
    op.drop_table('stock_adjustments')
    op.drop_table('restocking_requests')
    op.drop_table('orders')
    op.drop_table('notifications')
    op.drop_table('leftover_logs')
    op.drop_table('forecasts')
    op.drop_table('system_config')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
