"""sprint 3: waste management, portion feedback, staff scheduling

Revision ID: 8336fbe0315f
Revises: 7d60658b3d0f
Create Date: 2026-09-11 17:06:10.569076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8336fbe0315f'
down_revision: Union[str, None] = '7d60658b3d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waste_reduction_trends',
    sa.Column('trend_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_waste_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('trend_id')
    )
    op.create_table('portion_recommendations',
    sa.Column('recommendation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('leftover_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('suggested_portion_size', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.menu_item_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_table('shift_schedules',
    sa.Column('schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_period', sa.String(length=20), nullable=False),
    sa.Column('published_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['published_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('waste_logs',
    sa.Column('waste_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_ref_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity_wasted', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('waste_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.PrimaryKeyConstraint('waste_log_id')
    )
    op.create_table('shift_assignments',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(length=50), nullable=False),
    sa.Column('attendance_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['shift_schedules.schedule_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('shift_closing_reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('actual_order_volume', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['shift_schedules.schedule_id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('schedule_id')
    )
    op.create_table('staffing_recommendations',
    sa.Column('recommendation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('station', sa.String(length=50), nullable=False),
    sa.Column('recommended_staff_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.forecast_id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['shift_schedules.schedule_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staffing_recommendations')
    op.drop_table('shift_closing_reports')
    op.drop_table('shift_assignments')
    op.drop_table('waste_logs')
    op.drop_table('shift_schedules')
    op.drop_table('portion_recommendations')
    op.drop_table('waste_reduction_trends')
    # ### end Alembic commands ###
