"""checklist A1-A3: delivery verification lifecycle

Revision ID: d89450261840
Revises: 6ff739560035
Create Date: 2026-09-11 20:18:01.981148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd89450261840'
down_revision: Union[str, None] = '6ff739560035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('verified_by', sa.Integer(), nullable=True))
    op.add_column('deliveries', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'deliveries', 'users', ['verified_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_column('deliveries', 'verified_at')
    op.drop_column('deliveries', 'verified_by')
    # ### end Alembic commands ###
